### ISSUE TITLE
YouTube

### ISSUE THREAD

**Issue by deodoulos** [rishabh3354/VIZTUBE#3]
YouTube videos cannot be downloaded, from any website.

**Comment by rishabh3354** [comment]
please update the app to the latest version using cmd in terminal

sudo snap refresh viztube

Note: App will auto update in a day if you didnt manually update.
thanks for reporting, have a great day ahead.

**Comment by deodoulos** [comment]
Thank you; it did the trick.Could I suggest you send update notifications to your subscribers, if it isn't too much of a bother?Kind regardsSam(I was already thinking of sending you a coffee; it is not related to your email) 18.02.2023, 05:28, "Rishabh Bhardwaj" ***@***.***>: please update the app to the latest version using cmd in terminalsudo snap refresh viztube—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by rishabh3354** [comment]
Thanks for reporting. it is now fixed in new version of the app. i am closing this issue for now.
