### ISSUE TITLE
Doesn't download videos anymore

### ISSUE THREAD

**Issue by SpiritualCharlesDarwin** [rishabh3354/VIZTUBE#4]
It doesn't download videos anymore.  Says something about url can't be downloaded with excuses about private link or something, but it has always worked before and now doesn't work for any videos on youtube, rumble, etc...

**Comment by rishabh3354** [comment]
Hi @SpiritualCharlesDarwin could you send me video url so that i can check the issue. Thanks!

**Comment by SpiritualCharlesDarwin** [comment]
I just tried this one and it doesn't work:
https://www.youtube.com/watch?v=fWheqQLWrXY&t=424s

--Dennis

**Comment by rishabh3354** [comment]
![Screenshot from 2024-06-19 17-08-26](https://github.com/rishabh3354/VIZTUBE/assets/26843758/a1510998-1fc4-4f88-88f8-fc2f86d8ffe1)
For me it is working fine and i just downloaded with viztube

This might be country restricted video from youtube. Which country are you from? i checked with India

**Comment by SpiritualCharlesDarwin** [comment]
My VPN is set to Las Vegas, and that seems to be the problem.  I turn it
off and then it downloads, as I am in Canada and it is not restricted
here.  When I put the VPN back on, it will stop the download right in the
middle of operation.  Turn it off, and I can download again.  But, this
video is NOT restricted in the USA, as far as I know.  Were you able to
download from USA?

--Dennis

**Comment by rishabh3354** [comment]
Looks like vpn issue, here i don't have any issues. I connected to the USA , worked fine

**Comment by SpiritualCharlesDarwin** [comment]
Ok I'll update VPN or re-install, or perhaps contact them. Helps to narrow
it down. Thanks for the info.

**Comment by rishabh3354** [comment]
Thanks for reporting. it is now fixed in new version of the app. i am closing this issue for now.
